### ISSUE TITLE
어제부터 네이버 날씨를 불러오지 못하고 있습니다.

### ISSUE THREAD

**Issue by Murianwind** [miumida/naver_weather#27]
제 HA의 로그입니다.

로거: homeassistant.helpers.entity
소스: helpers/entity.py:942
처음 발생: 13:13:57 (14 발생)
마지막 로그인: 15:29:54

Update for weather.naver_weather fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/naver_weather/weather.py", line 147, in async_update
    await self.api.update()
  File "/config/custom_components/naver_weather/api_nweather.py", line 322, in update
    gbVal = li.select_one("span.txt").text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

이 오류는 사용자 통합구성요소에서 발생했습니다.

로거: custom_components.naver_weather.api_nweather
소스: custom_components/naver_weather/api_nweather.py:580
통합구성요소: 네이버 날씨 (관련 문서)
처음 발생: 13:03:55 (17 발생)
마지막 로그인: 15:34:31

Failed to update NWeather API status Error: 403, message='Forbidden', url='https://search.naver.com/search.naver?query=%EC%8B%A0%EB%82%B42%EB%8F%99+%EB%82%A0%EC%94%A8'
Failed to update NWeather API status Error: 'NoneType' object has no attribute 'text'

로거: homeassistant.components.weather
소스: helpers/entity_platform.py:595
통합구성요소: 날씨 (관련 문서, 문제)
처음 발생: 14:29:51 (2 발생)
마지막 로그인: 15:34:31

Error adding entity weather.naver_weather for domain weather with platform naver_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/naver_weather/nweather_device.py", line 70, in async_added_to_hass
    await self.api.update()
  File "/config/custom_components/naver_weather/api_nweather.py", line 322, in update
    gbVal = li.select_one("span.txt").text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

로거: homeassistant.helpers.frame
소스: helpers/frame.py:155
처음 발생: 13:03:50 (8 발생)
마지막 로그인: 15:34:31

Detected code that calls async_forward_entry_setup for integration naver_weather with title: 날씨 and entry_id: 8a2834f4cbfda43fa8dfc833834b6871, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

로거: homeassistant.components.websocket_api.http.connection
소스: custom_components/naver_weather/weather.py:158
통합구성요소: Home Assistant WebSocket API (관련 문서, 문제)
처음 발생: 13:09:31 (20 발생)
마지막 로그인: 15:39:59

[281472133901776] Error handling message: Unknown error (unknown_error) 송홍진 from 223.39.207.15 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 18.1.0) Mobile/HomeAssistant, like Safari)
[281472890249008] Error handling message: Unknown error (unknown_error) 송홍진 from 115.93.38.38 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36)
[281471986489888] Error handling message: Unknown error (unknown_error) 송홍진 from 223.39.206.174 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 18.1.0) Mobile/HomeAssistant, like Safari)
[281472239218128] Error handling message: Unknown error (unknown_error) 송홍진 from 223.39.206.63 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 18.1.0) Mobile/HomeAssistant, like Safari)
[281471946600176] Error handling message: Unknown error (unknown_error) 송홍진 from 223.39.206.63 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 18.1.0) Mobile/HomeAssistant, like Safari)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/weather/websocket_api.py", line 99, in ws_subscribe_forecast
    await entity.async_update_listeners({forecast_type})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 968, in async_update_listeners
    native_forecast_list: list[Forecast] | None = await getattr(
                                                  ^^^^^^^^^^^^^^
  File "/config/custom_components/naver_weather/weather.py", line 131, in async_forecast_daily
    return self._forecast(WeatherEntityFeature.FORECAST_DAILY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/naver_weather/weather.py", line 158, in _forecast
    for data in self.api.forecast:
                ^^^^^^^^^^^^^^^^^
AttributeError: 'NWeatherAPI' object has no attribute 'forecast'

현재 제 HA는

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
프론트엔드 20241002.4

입니다.

**Comment by raysonxgithub** [comment]
저도 같은 문제예요ㅠㅠㅠ

**Comment by YunsuChoi** [comment]
같은 문제가 발생하고 있습니다.
